Vagrant.configure("2") do |config|
  
  number_of_machines = 5
  box_name = "ubuntu/bionic64"
  zookeeper_folder = "apache-zookeeper-3.5.5-bin" 
  zookeeper_file = "#{zookeeper_folder}.tar.gz"

  base_ip = 100
  base_ip_addresses = "192.168.51"
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }
  zookeeper_servers_config = (1..number_of_machines).map{ |i| "server.#{i}=#{ip_addresses[i-1]}:2888:3888\n" }.join("")
  zookeeper_config = <<-ZOOCFG
    tickTime=2000
    dataDir=/var/lib/zookeeper
    clientPort=2181
    initLimit=5
    syncLimit=2
    4lw.commands.whitelist=stat, ruok, conf, isro
    #{zookeeper_servers_config}      
  ZOOCFG

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "box_#{i}" do |box|

      box.vm.box = box_name
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"

      box.vm.provision "file", source: "~/Downloads/#{zookeeper_file}", destination: "/home/vagrant/"
            
      box.vm.provision "shell", inline: "sudo apt install -y default-jre"
      box.vm.provision "shell", inline: "[ ! -e /opt/#{zookeeper_folder} ] && sudo tar zxvf #{zookeeper_file} -C /opt || echo 'zookeeper has been extracted' "
            box.vm.provision "shell", inline: "echo '#{zookeeper_config.strip}' > /opt/#{zookeeper_folder}/conf/zoo.cfg"
      box.vm.provision "shell", inline: "sudo mkdir -p /var/lib/zookeeper && echo #{i} | sudo tee /var/lib/zookeeper/myid"
      box.vm.provision "shell", inline: "sudo /opt/#{zookeeper_folder}/bin/zkServer.sh start"

    end
  end
end
