Vagrant.configure("2") do |config|
  
  number_of_machines = 5
  box_name = "ubuntu/bionic64"
  zookeeper_folder = "apache-zookeeper-3.5.5-bin" 
  zookeeper_install_file = "#{zookeeper_folder}.tar.gz"

  base_ip = 100
  base_ip_addresses = "192.168.51"
  # we will create ip address from 192.168.51.100 onward
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }

  # this two variables are to populate zookeeper configuration
  zookeeper_servers_config = (1..number_of_machines).map{ |i| "server.#{i}=#{ip_addresses[i-1]}:2888:3888\n" }.join("")
  zookeeper_config = <<-ZOOCFG
    tickTime=2000
    dataDir=/var/lib/zookeeper
    clientPort=2181
    initLimit=5
    syncLimit=2
    4lw.commands.whitelist=stat, ruok, conf, isro
    #{zookeeper_servers_config}      
  ZOOCFG

  # script to provision and start zookeeper
  script = <<-SCRIPT
    sudo apt install -y default-jre
    [ ! -e /opt/#{zookeeper_folder} ] && sudo tar zxvf #{zookeeper_install_file} -C /opt || echo 'zookeeper has been extracted' 
    echo '#{zookeeper_config.strip}' > /opt/#{zookeeper_folder}/conf/zoo.cfg
    sudo /opt/#{zookeeper_folder}/bin/zkServer.sh start
  SCRIPT

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "box_#{i}" do |box|
      box.vm.box = box_name
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"

      box.vm.provision "file", source: "~/Downloads/#{zookeeper_install_file}", destination: "/home/vagrant/"
            
      # set myid file in each machine required by zookeeper cluster
      box.vm.provision "shell", inline: "sudo mkdir -p /var/lib/zookeeper && echo #{i} | sudo tee /var/lib/zookeeper/myid"

      box.vm.provision "shell", inline: "#{script}"
    
    end
  end
end
