Vagrant.configure("2") do |config|
  
  number_of_machines = 5
  box_name = "ubuntu/bionic64"

  base_ip = 100
  base_ip_addresses = "192.168.51"
  # we will create ip address from 192.168.51.100 onward
  ip_addresses = (1..number_of_machines).map{ |i| "#{base_ip_addresses}.#{base_ip + i}" }

  # provisioning script
  # Add all required setup here
  script = <<-SCRIPT
    echo "hello world"
  SCRIPT

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end
  
  (1..number_of_machines).each do |i|
    config.vm.define "box_#{i}" do |box|
      box.vm.box = box_name
      box.vm.network "private_network", ip: "#{ip_addresses[i-1]}"

      # provision the script
      box.vm.provision "shell", inline: "#{script}"    
    end
  end
end
