Vagrant.configure("2") do |config|
  base_ip = 100
  n = 3
  box_name = "ubuntu/bionic64"

  (1..n).each { |i|
    config.vm.define "box_#{i}" do |box|
      box.vm.provision "shell", inline: "echo hello world from box_#{i}"
      box.vm.box = box_name
      box.vm.network "private_network", ip: "192.168.56.#{base_ip + i}"
    end
  }
end
